# Generated by Django 5.1.3 on 2024-11-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_branch_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='name2',
        ),
    ]
